@SERVICE_PORT = 3020

# Get all posts

GET http://localhost:{{SERVICE_PORT}}/api/posts HTTP/1.1

###

# Get posts with filter

GET http://localhost:{{SERVICE_PORT}}/api/posts?limit=2&sortDirection=desc&tags[]=6260c22b-870d-49b2-b9fb-e929486bfe0c&page=1 HTTP/1.1

###

# Get post by id
GET http://localhost:{{SERVICE_PORT}}/api/posts/0eb6c19a-962c-4fc7-9106-7d46b09aaab8z HTTP/1.1

###

# Create a new video post
POST http://localhost:{{SERVICE_PORT}}/api/posts/create HTTP/1.1
Content-Type: application/json

{
  "title": "Пост видео 001",
  "type": "VIDEO",
  "authorId": "658ede7600f80970fcf9e111",
  "tags": ["dbca7781-e730-4fa4-b03a-e49ffb49a04d", "dc46bf2e-130a-4f7d-a8c6-31bef09445b0"],
  "postVideo": {
    "urlYoutube": "https://youtu.be/lwYWMHVwYrs?si=2YnJzt-m7xxa0MTZ"
  }
}

###

# Create a new text post
POST http://localhost:{{SERVICE_PORT}}/api/posts/create HTTP/1.1
Content-Type: application/json

{
  "title": "Пост текст 001",
  "type": "TEXT",
  "authorId": "658ede7600f80970fcf9e111",
  "tags": ["60a40c1a-a844-48d9-9c65-a45aad0b4d80", "9faee213-ff82-4673-a502-a616ac9fdde1"],
  "postText": {
    "announcement": "some announcement",
    "content": "some content"
  }
}

###

# Create a new quote post
POST http://localhost:{{SERVICE_PORT}}/api/posts/create HTTP/1.1
Content-Type: application/json

{
  "title": "Пост цитата 001",
  "type": "QUOTE",
  "authorId": "658ede7600f80970fcf9e111",
  "tags": ["60a40c1a-a844-48d9-9c65-a45aad0b4d80", "9faee213-ff82-4673-a502-a616ac9fdde1"],
  "postQuote": {
    "quoteContent": "some quote content"
  }
}

###

# Create a new photo post
POST http://localhost:{{SERVICE_PORT}}/api/posts/create HTTP/1.1
Content-Type: application/json

{
  "title": "Пост фото 001",
  "type": "PHOTO",
  "authorId": "658ede7600f80970fcf9e111",
  "tags": ["60a40c1a-a844-48d9-9c65-a45aad0b4d80", "9faee213-ff82-4673-a502-a616ac9fdde1"],
  "postPhoto": {
    "photoId": "658ede7600f80970fcf9e231"
  }
}

###

# Create a new link post
POST http://localhost:{{SERVICE_PORT}}/api/posts/create HTTP/1.1
Content-Type: application/json

{
  "title": "Пост ссылка 001",
  "type": "LINK",
  "authorId": "658ede7600f80970fcf9e111",
  "tags": ["60a40c1a-a844-48d9-9c65-a45aad0b4d80", "9faee213-ff82-4673-a502-a616ac9fdde1"],
  "postLink": {
    "url": "some-link",
    "description": "some description"
  }
}

###

# Create a new photo post
POST http://localhost:{{SERVICE_PORT}}/api/posts/create HTTP/1.1
Content-Type: application/json

{
  "title": "Пост фото 001",
  "type": "PHOTO",
  "authorId": "658ede7600f80970fcf9e111",
  "tags": [],
  "postPhoto": {
    "photoId": "some photo Id"
  }
}

###

# Delete the post by id
DELETE http://localhost:{{SERVICE_PORT}}/api/posts/3334c986-c033-4a56-8e56-61e2d0ac82b3 HTTP/1.1

###

# Update post by id
PATCH http://localhost:{{SERVICE_PORT}}/api/posts/5ad61f46-3107-420f-b6a0-cf8ada0f780f HTTP/1.1
Content-Type: application/json

{
  "title": "Обновлённый пост",
  "type": "LINK",
  "postLink": {
    "url": "some-link"
  }
}

###

# Create a new comment for post
POST http://localhost:{{SERVICE_PORT}}/api/posts/e2527346-5449-4057-90b0-6bec1c538acd/comments HTTP/1.1
Content-Type: application/json

{
  "content": "This is text",
  "authorId": "65990102bb965b742900ba59"
}

###
