
@SERVICE_PORT = 3000
# Create a new user
POST http://localhost:{{SERVICE_PORT}}/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user345@notfound.local",
  "username": "Neo",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:{{SERVICE_PORT}}/api/users/6628e2693a0e1a3b6b254f97 HTTP/1.1

###

# Login user by email and password
POST http://localhost:{{SERVICE_PORT}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}
