@SERVICE_PORT = 3030

# Upload some file
POST http://localhost:{{SERVICE_PORT}}/api/uploader/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="22-600x400.jpg"

< ./mock/22-600x400.jpg

--boundary--

###
